### ISSUE TITLE
PNPM only?

### ISSUE THREAD

**Issue by chupzzz** [kaivanwong/astro-theme-vitesse#1]
Can't install, because I don't have a PNPM. What if all my projects and workflow based on YARN and I'm happy with it?

Dictatorship.
Delete and forget.

**Comment by kieranwv** [comment]
I've fixed it and now it uses npm by default, and you can easily switch to yarn by going through the [documentation steps](https://github.com/kaivanwong/astro-theme-vitesse#use-pnpm--yarn).

**Comment by chupzzz** [comment]
Checked with NPM: it works from the first spin

Great, thanks!
