### ISSUE TITLE
Table of Contents support

### ISSUE THREAD

**Issue by vinhphm** [kaivanwong/astro-theme-vitesse#2]
First, a great thank you for your work on porting the theme to Astro. Now is there any chance we can have the Table of Contents (TOC) just like the original theme as well?

**Comment by kieranwv** [comment]
> First, a great thank you for your work on porting the theme to Astro. Now is there any chance we can have the Table of Contents (TOC) just like the original theme as well?

Thank you very much for your use. This template has top navigation and podcast categories for you to use. If it doesn't meet your needs, you can migrate your original functional code to a new project.
